# Generated by Django 5.0.4 on 2025-02-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dons', models.IntegerField()),
            ],
            options={
                'db_table': 'compte',
            },
        ),
    ]
